### ISSUE TITLE
Spider Daemon links to localhost?

### ISSUE THREAD

**Issue by wrinkl3** [ciscocsirt/malspider#10]
I'm trying to run malspider on a remote server. I'm accessing the dashboard just fine using "serveripaddress":8080. However, all the links from the dashboard that are supposed to lead to the spider daemon are given as "http://localhost:6802", which seems to be a hardcoded address. Manually changing localhost to "serveripaddress" doesn't seem to help. How do I fix it?

**Comment by jasheppa5** [comment]
Hi Alex,

It's a bug in the code - The spider daemon should be accessed via the
scrapyd api from django and not directly. I'll probably remove the links
completely in the next release until I recode a custom daemon page.

-James
