### ISSUE TITLE
Are jobs really cancelled?

### ISSUE THREAD

**Issue by r3comp1le** [ciscocsirt/malspider#2]
`python malspider_django/manage.py manage_spiders`
Canceling all outstanding jobs
canceled job  261c094631af11e6872f79b4a0de6dd8  for project ' malspider '
canceled job  8976429e31b011e6872f79b4a0de6dd8  for project ' malspider '

`ps -aux`
 /usr/bin/python -m scrapyd.runner crawl full_domain -a _job=261c094631af11e6872f79b4a0de6dd8 -a org=1708 .....
 /usr/bin/python -m scrapyd.runner crawl full_domain -a _job=8976429e31b011e6872f79b4a0de6dd8 -a org=1707 ....

**Comment by jasheppa5** [comment]
Hi,

Jobs are scheduled once every 24 hours. If a job is still running after 24
hours there is a good chance the job is hung or the connection/response
time is very slow - for that reason Malspider cancels any hanging jobs
after 24 hours to make room for new crawls.

If a job still appears to be running even after the manage_spiders command
calls the scrapyd API cancel function, then I'm not sure where the problem
lies. Jobs should be terminated. Are you still seeing jobs with ps -aux
several minutes after cancelation?  if there is a bug in the scrapyd API
the only other way to cancel jobs immediately is to make a direct call to
the underlying scrapyd sqllite database.

-James

**Comment by r3comp1le** [comment]
Yes, the jobs are still there after it says it cancelled them. Going on +1 hour since cancellation attempt.

**Comment by r3comp1le** [comment]
Very odd, still running even after:

` curl http://localhost:6802/cancel.json -d project=malspider -d job=261c094631af11e6872f79b4a0de6dd8
{"status": "ok", "prevstate": "running"}`

**Comment by jasheppa5** [comment]
Just curious, does the job still show as active after you manually "kill"
the process?

I'm going to look into this further and see if I can reproduce the issue
and attach a debugger to the spider.

**Comment by r3comp1le** [comment]
For some reason kill wasnt doing anything. I eventually rebooted. Appreciate the help.

**Comment by r3comp1le** [comment]
I ran into this issue again tonight.  I went from 1 org for testing, to 10 orgs and ran spider.  5 jobs finished, while 5 were still running.  The elements and pages werent incrementing anymore either.

**Comment by r3comp1le** [comment]
Check again this morning and now have 11 running jobs

**Comment by jasheppa5** [comment]
I added a few lines of code to force a timeout after crawling a domain for "X" amount of time. Early testing seems to indicate this fixes the issue with the spider hanging on certain domains.
