### ISSUE TITLE
Regex Raw field

### ISSUE THREAD

**Issue by r3comp1le** [ciscocsirt/malspider#3]
Is it possible to regex on the raw data? If so, whats the proper method?

`clicky_regex = re.compile("clicky", re.IGNORECASE | re.MULTILINE)`

`clicky_elements = Element.objects.filter(Q(event_time__gte=search_start_time), Q(tag_name='script') | Q(tag_name='iframe'), Q(raw__regex=clicky_regex))`

**Comment by jasheppa5** [comment]
The syntax looks correct. You need to register your alert with the
generate_alerts function. If your alert looks like this:

    *def get_clicky_malware**(self,search_start_time):*
>         clicky_regex = re.compile("clicky", re.IGNORECASE | re.MULTILINE)
>         clicky_elements = Element.objects.filter(Q(event_time__gte=search_start_time),
> Q(tag_name='script') | Q(tag_name='iframe'), Q(raw__regex=clicky_regex))
>         return click_elements


then go into the generate_alerts function and register with the alerts
dictionary:

alerts["CLICKY MALWARE"] = self.get_clicky_malware(search_start_time)

If you don't want to a whitelist check to be performed on your results you
can register the alert under the "alerts_nocheck" dictionary instead.


Let me know if this fixes your problem.

**Comment by r3comp1le** [comment]
Yup, had it listed under nocheck section, but still not firing.

Database Views:
http://i.imgur.com/Wazt95g.png
http://i.imgur.com/xS0qft7.png

**Comment by jasheppa5** [comment]
First, thank you for your persistence and patience. I spotted the problem:

raw__regex=clicky_regex

should be

raw__regex=clicky_regex*.pattern*

You need to pass the regex pattern string, not the regex object. I realize
I have at least one sample classification that does the same thing so I'll
fix that in a code update today or tomorrow.

I ran a simple test and it worked so hopefully this fixes your problem.
Thanks again for your patience, and PLEASE add your final signature to
github!!

-James

**Comment by r3comp1le** [comment]
wow, I cant believe I didnt see that.  Out of all the existing rules I cloned as an example, it was the one missing .pattern, (def get_cart_id_injections)  lol.

Works perfect now.

**Comment by jasheppa5** [comment]
Do you mind submitting a pull request so your clicky rule can be added to
the master repo? I can also add you as a contributor if you like, and that
will give you direct read/write access to the repo.
